// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aGnUk3fm0kJf6VhfbGC7BybeoNyrWk0',
    appId: '1:228706990679:web:5f17913960ded081eec112',
    messagingSenderId: '228706990679',
    projectId: 'sample1-8dfb3',
    authDomain: 'sample1-8dfb3.firebaseapp.com',
    storageBucket: 'sample1-8dfb3.firebasestorage.app',
    measurementId: 'G-2EE57055Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD29G2_xSb_flH_9-7g56USm5L5eOv2-w',
    appId: '1:228706990679:android:d9880f1602b88ef7eec112',
    messagingSenderId: '228706990679',
    projectId: 'sample1-8dfb3',
    storageBucket: 'sample1-8dfb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqO5uX6MURqhDqEr1tFKxdwCkgheAH64',
    appId: '1:228706990679:ios:34ca62d4b3122d59eec112',
    messagingSenderId: '228706990679',
    projectId: 'sample1-8dfb3',
    storageBucket: 'sample1-8dfb3.firebasestorage.app',
    iosBundleId: 'com.example.mitraPix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqO5uX6MURqhDqEr1tFKxdwCkgheAH64',
    appId: '1:228706990679:ios:34ca62d4b3122d59eec112',
    messagingSenderId: '228706990679',
    projectId: 'sample1-8dfb3',
    storageBucket: 'sample1-8dfb3.firebasestorage.app',
    iosBundleId: 'com.example.mitraPix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-aGnUk3fm0kJf6VhfbGC7BybeoNyrWk0',
    appId: '1:228706990679:web:253e1777b3f6ff35eec112',
    messagingSenderId: '228706990679',
    projectId: 'sample1-8dfb3',
    authDomain: 'sample1-8dfb3.firebaseapp.com',
    storageBucket: 'sample1-8dfb3.firebasestorage.app',
    measurementId: 'G-53KFH3S9N8',
  );
}
